pipeline:
  publish:
    image: plugins/docker
    repo: doconce/texlive
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    tag: [ latest ]
    when:
      branch: master
      event: push
